.circleci/config.yml

@bpostlethwaite @rpkyle FYI..!!

Fix auto deploys for r

---

apps/dash-wind-streaming/app.py
apps/dash-wind-streaming/assets/style.css

Playground Link: https://dash-playground.plotly.host/dash-wind-streaming/
Changes
- mobile view for dash-wind-streaming

mobile view for wind streaming

---

apps/dash-drug-discovery/assets/plotly_ga.js
apps/dash-tsne/assets/plotly_ga.css
apps/dash-wind-streaming/assets/plotly_ga.js
predeploy.py

Closes #138. 
Added an environment variable in CircleCI with the name `DASH_GA_CODE` that contains the Google Analytics code, and modified the predeploy script to inject that code in an `app.index_string` just above `app.layout` for the app being deployed.  
The script was added into the default `app.index_string` (https://github.com/plotly/dash/blob/7b23e7960f8788fe9050dc2008c99bcc765d0571/dash/dash.py#L40).

Add code to inject Google Analytics script.

---

apps/dash-mapd-demo/app.py
apps/dash-mapd-demo/docker/Dockerfile
apps/dash-mapd-demo/docker/deployment/omnisci-deployment.yml

Issue for app: #333 
Specifying `2` in the prompt allows us to download the 10K dataset instead of the default 7M dataset.

Use smaller dataset

---

apps/dash-nlp/app.py
apps/dash-nlp/precomputing.py

I am improving an existing app Dash-NLP

[sample-apps] Dash-NLP: Precomputed LDA file and fix the app

---

apps/dash-ocean-optics/README.md

Redeploy this app on master branch after circle-ci fix https://github.com/plotly/dash-sample-apps/commit/7c34be8edf736c937031b75fb9c8810bf8512e8f

Updt readme

---

apps/dash-lunar-lander/app.py

Issue for app: https://github.com/plotly/dash-customer-success/issues/206
- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-lunar-lander
- Current gallery app URL: (delete this line if inapplicable): https://dash-gallery.plotly.host/dash-lunar-lander
readable and, where it isn't, it …

adding loading screen for graph

---

apps/dash-lunar-lander/app.py

RE: Request from lunar lander app author to change description text in app
- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-lunar-lander/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-lunar-lander/
readable and, where it isn't, it has been commented …

updating app description

---

.circleci/config.yml
apps/dash-live-model-training/app.py
apps/dash-stitching/app.py
apps/dash-tsne/demo.py

Comparison to none should be 'if cond is none:'.
Lint Python code for rule E711.
https://www.flake8rules.com/rules/E711.html

Add flake8 to CircleCI and enable rule E711.

---

.circleci/config.yml
apps/dash-brain-viewer/app.py
apps/dash-brain-viewer/mni.py
apps/dash-cytoscape-phylogeny/app.py
apps/dash-cytoscape/app.py
apps/dash-daq-iv-tracer/demo.py
apps/dash-lunar-lander/app.py
apps/dash-manufacture-spc-dashboard/app.py
apps/dash-mes-form-submission/app.py
apps/dash-multipage-report/app.py
apps/dash-nlp/app.py
apps/dash-nlp/wordcloud_matplotlib.py
apps/dash-ocean-optics/app.py
apps/dash-phylogeny/utils.py
apps/dash-stitching/app.py
apps/dash-stitching/registration.py
apps/dash-tsne/local.py
apps/dash-uber-rides-demo/app.py
apps/dash-web-trader/app.py
apps/dash-wind-streaming/db/api.py
apps/dash-yield-curve/app.py

Lint Python.
Rules added -
Whitespace before ':' (E203)
Block comment should start with '# ' (E265)
Trailing whitespace (W291)
https://www.flake8rules.com/rules/E203.html
https://www.flake8rules.com/rules/E265.html
https://www.flake8rules.com/rules/W291.html
refs #388 
Hey @josegonzalez I would like add more Flake8 rules.

Add three more Flake8 rules to the CircleCI build.

---

.circleci/config.yml
apps/dash-brain-viewer/mni.py
apps/dash-lunar-lander/app.py
apps/dash-phylogeny/utils.py
apps/dash-stitching/app.py
apps/dash-stitching/registration.py
apps/dash-web-trader/app.py

Closes #406
This fixes an issue with over-zealously applying lint fixes to code that aren't actually resolving PEP8.
N/A

fix: remove E203 and apply black

---

apps/dash-daq-tektronix350/app_mock.py
apps/dash-daq-tektronix350/assets/tektronix.css

Issue for app: https://github.com/plotly/dash-sample-apps/issues/412
- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-daq-tektronix350/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-daq-tektronix350/
readable and, where it isn't, it has been commented …

Removing color picker and adjusting css. Also, Robs first commit

---

apps/dash-daq-tektronix350/requirements.txt

Issue for app: https://github.com/plotly/dash-sample-apps/issues/416
- Playground deployment URL (new version):No

dash-daq-tektronix350 - change dash version to dash 1.8.0

---

apps_directory_mapping.py

This was removed as part of the new deploys refactor.
N/A

chore: delete unused file

---

apps/dash-daq-satellite-dashboard/app.py
apps/dash-medical-provider-charges/app.py
apps/dash-oil-and-gas/app.py
apps/dash-oil-gas-ternary/app.py
apps/dash-opioid-epidemic/app.py
apps/dash-phylogeny/app.py
apps/dash-spatial-clustering/app.py
apps/dash-uber-rides-demo/app.py
apps/dashr-medical-provider-charges/app.R
apps/dashr-oil-and-gas-ternary/app.R
apps/dashr-oil-and-gas/app.R
apps/dashr-opiod-endemic/app.R
apps/dashr-uber-rasterizer/app.R
apps/dashr-uber-rides/app.R

rotate mapbox token

---

apps/dash-medical-provider-charges/app.py
apps/dash-medical-provider-charges/requirements.txt

Upgrading this app to use `dash==1.12.0` . The upgrade will allow for a domain restriction to be placed on the mapbox token for the gallery apps without encountering map rendering issues. See https://github.com/plotly/dash-sample-apps/issues/426 for details
- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-medical-provider-charges/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-medical-provider-charges/
the style …

upgrading medical-provider-charges to dash 1.12.0, linting code

---

apps/dash-cytoscape-lda/app.py

[Fix] Dash Cytoscape LDA: Change caching from filesystem to Redis

---

apps/dash-cytoscape-lda/app.py

- Playground deployment URL https://dash-playground.plotly.host/dash-cytoscape-lda/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-cytoscape-lda/
- Python app repository link: 
lessen the volume …

[FIX] Dash Cytoscape LDA: Speed up tsne to prevent app timeouts occurring on dash-gallery

---

apps/dash-opioid-epidemic/requirements.txt

The [CircleCI tests](https://circleci.com/gh/plotly/dash-sample-apps/6065) are currently failing because of plotly vs cufflinks version mismatch:
```
remote:          File "/app/app.py", line 10, in <module>        
remote:            import cufflinks as cf        
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/cufflinks/__init__.py", line 21, in <module>        
remote:            from .plotlytools import *        
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/cufflinks/plotlytools.py", line 2, in <module>        
remote:            import chart_studio.plotly as py        
remote:        ModuleNotFoundError: No module named 'chart_studio.plotly'        
remote:        [2020-05-15 18:43:50 +0000] [203] …
```

[FIX] Update dash-opioid-epidemics requirements to pass CircleCI tests

---

apps/dash-summarize/app.py

Dash Summarize: Change default model, use fp16

---

apps/dash-loan-grade/.buildpacks

Add Buildpack to dash-loan to fix tests

---

apps/dash-image-segmentation/app.py
apps/dash-image-segmentation/use_ml_image_segmentation_classifier.py

Makes it possible to run the classifier the app "learned" on an image locally with the included script `use_ml_image_segmentation_classifier.py`.
Makes it so you don't need the "Save Classifier" button: pressing the "Download classifier" or "Download classified image" button will then fill the respective `dcc.Store` with the classifier or classified image and then make a blob and make this available for download. Otherwise `dash.no_update` is passed to the `dcc.Store`s (like before).

joblib trainable seg: fixed script regression and integrated "Save Classifier" into existing buttons.

---

apps/dash-image-enhancing/README.md

Correct Typo

---

apps/dash-gpt3-chatbot/README.md

Add disclaimer for GPT3 Chatbot

---

apps/dash-deck-explorer/app.py

Update Dash Deck Explorer URL

---

apps/dash-deck-explorer/app.py

Fix Dash Deck Explorer path

---

apps/dash-deck-explorer/app.py

Change URL update problem caused by dropdown

---

apps/dashr-uber-rasterizer/app.R

Issue for app: plotly/streambed#14992
As part of the issue above, this PR applies a small fix to the layout of the app so that it can successfully deploy and start with the updated version of Dash for R. 
- Playground deployment URL: https://github.com/plotly/dash-sample-apps/tree/fix-uber-rasterizer/apps/dashr-uber-rasterizer

Fixing layout

---

apps/dash-oil-and-gas/.gitignore
apps/dash-oil-and-gas/app.py
apps/dash-spatial-clustering/helpers.py

- apps/dash-oil-and-gas/data/Oil_and_Gas_Annual_Production__1985_-_2000.csv
- apps/dash-oil-and-gas/data/Oil_and_Gas_Annual_Production__Beginning_2001.csv
- apps/dash-oil-and-gas/data/wellspublic.csv
- apps/dash-spatial-clustering/data/listings.csv
- apps/dashr-oil-and-gas/data/Oil_and_Gas_Annual_Production__1985_-_2000.csv
- apps/dashr-oil-and-gas/data/Oil_and_Gas_Annual_Production__Beginning_2001.csv
They were all moved to https://github.com/plotly/datasets/tree/master/dash-sample-apps/dash-oil-and-gas/data

Remove large CSV files

---

apps/dash-salesforce-crm/README.md

Issue for app: #[issue number here] https://plotly.slack.com/archives/CN8DUM6JF/p1604327154424200
API key expired. I regenerated an account and updated the env variables. This PR is to trigger a redeploy
I have …

Salesforce crm redeploy

---

apps/dash-label-properties/README.md

minimal PR to deploy dash-label-properties-app (actually found something useful to fix)

update app name in README.md

---

apps/dash-datashader/README.md

Closes #https://github.com/plotly/dash-sample-apps/issues/531
readable and, where it isn't, …

Fix dash-datashader

---

apps/dash-covid-xray/requirements.txt

@nicolaskruchten I bumped the dash requirement to the latest release, which corrects the layout update bug. I need an approval to merge and deploy.

bump dash requirement

---

apps/dash-vtk-explorer/explorer.py

Fix requirements in dash-vtk-explorer

---

apps/dash-vtk-explorer/demos/pyvista-point-cloud/app.py
apps/dash-vtk-explorer/demos/pyvista-point-cloud/requirements.txt
apps/dash-vtk-explorer/demos/pyvista-terrain-following-mesh/app.py
apps/dash-vtk-explorer/demos/slice-rendering/app.py
apps/dash-vtk-explorer/demos/synthetic-volume-rendering/app.py
apps/dash-vtk-explorer/demos/usage-algorithm/app.py
apps/dash-vtk-explorer/demos/usage-vtk-cfd/app.py
apps/dash-vtk-explorer/demos/volume-rendering/app.py
apps/dash-vtk-explorer/explorer.py

Improve vtk explorer

---

apps/dash-salesforce-crm/README.md

Salesforce credentials expired. I created a new account and added the new credentials as env variables.

trigger dash-salesforce-app deploy

---

apps/dash-vtk-explorer/demos/pyvista-point-cloud/app.py
apps/dash-vtk-explorer/demos/slice-rendering/app.py
apps/dash-vtk-explorer/demos/synthetic-volume-rendering/requirements.txt
apps/dash-vtk-explorer/demos/usage-vtk-cfd/app.py
apps/dash-vtk-explorer/demos/usage-vtk-cfd/requirements.txt
apps/dash-vtk-explorer/demos/volume-rendering/requirements.txt

Updates to vtk-cfd demo

---

apps/dash-vtk-explorer/README.md

Add vtk readme

---

apps/dash-soccer-analytics/app.py

Dash soccer analytics: Change default event file to first

---

apps/dash-floris-flow/requirements.txt

Fix floris-flow

---

apps/dash-floris-gch/requirements.txt

Change pyproj requirement for floris-gch

---

README.md

Change wording in readme

---

.github/pull_request_template.md
.github/workflows/main.yml

Change default version bump to patch, update PR instructions

---

apps/dash-soccer-analytics/app.py
apps/dash-soccer-analytics/event_plotter.py
apps/dash-soccer-analytics/initial_figures.py
apps/dash-soccer-analytics/requirements.txt

Update soccer analytics app

---

apps/dash-baseball-statistics/index.py
apps/dash-baseball-statistics/navbar.py

Fix URL paths for baseball app

---

apps/dash-peaky-finders/install.sh
apps/dash-peaky-finders/requirements-predeploy.txt

Peaky Finders: Reroll to original requirements.txt, fix pip

---

apps/dash-turbine-maintenance/app.py

Update the Turbine Predictive Maintenance App

---

apps/dash-vehicle-geometry/app.py

Fix dash vehicle geometry

---

apps/dash-turbine-maintenance/app.py
apps/dash-turbine-maintenance/data_preprocessing.py

Update Turbine Maintenance app from original repo

---

apps/dash-pileup-demo/app.py
apps/dash-pileup-demo/assets/dash-pileup.css

updated RNA-seq tutorial description in pileup.js demo app

---

apps/dash-pileup-demo/app.py
apps/dash-pileup-demo/assets/dash-pileup.css

originally authored by @akmorrow13 in #613 
readable and, where it isn't, it has been …

updated RNA-seq tutorial description in pileup.js demo app (original: #613)

---

apps/dash-deit/Procfile
apps/dash-dino/.gitignore
apps/dash-dino/Procfile
apps/dash-dino/README.md
apps/dash-dino/app.py
apps/dash-dino/requirements.txt

Add dash dino app (#minor)

---

apps/dash-aerosandbox/app.py
apps/dash-avs-explorer/app.py
apps/dash-baseball-statistics/app.py
apps/dash-brain-viewer/app.py
apps/dash-clinical-analytics/app.py
apps/dash-financial-report/app.py
apps/dash-image-processing/app.py
apps/dash-interest-rate/app.py
apps/dash-live-model-training/app.py
apps/dash-manufacture-spc-dashboard/app.py
apps/dash-medical-provider-charges/app.py
apps/dash-multipage-report/app.py
apps/dash-object-detection/app.py
apps/dash-oil-and-gas/app.py
apps/dash-opioid-epidemic/app.py
apps/dash-peaky-finders/peaky_app.py
apps/dash-phylogeny/app.py
apps/dash-pk-calc/app.py
apps/dash-spatial-clustering/app.py
apps/dash-svm/app.py
apps/dash-tsne/app.py
apps/dash-uber-rides-demo/app.py
apps/dash-web-trader/app.py
apps/dash-wind-streaming/app.py
apps/dash-yield-curve/app.py

Add title to popular apps

---

.deployignore
apps/dash-aix360-heart/README.md

Uningnore aix360

---

apps/dash-3d-image-partitioning/requirements.txt
apps/dash-aix360-heart/requirements.txt
apps/dash-canvas-ocr/requirements.txt
apps/dash-cytoscape-lda/requirements.txt
apps/dash-object-detection/requirements.txt
apps/dash-tsne/requirements.txt

Update dependencies based on advisories

---

apps/dash-loan-grade/app.py

* Add a title to the app for better SEO

Change the title of the loan grade app

---

apps/dash-web-trader/app.py

redeploy due to container issues

---

apps/dash-airfoil-design/app.py
apps/dash-pileup-demo/assets/general-app-page.css
apps/dash-pileup-demo/layout_helper.py

Add "Enterprise Demo" and "Source code" buttons

---

apps/dash-oil-and-gas/app.py

Update app.py with Mingo's new app

---

apps/dash-oil-and-gas/requirements.txt

Update requirements.txt with Mingo's new app
