.circleci/config.yml
Previously, in the script, `.github/ISSUE_TEMPLATE` would count as part of the diff during the gallery deployment, which caused it to fail.
=> Fix gallery upload script to only look in apps/ directory.

predeploy.py
This PR makes a minor change to the logic of `predeploy.py` such that the script does not attempt to copy a `requirements.txt` script if the app name begins with `dashr-`.
=> Fix bug in predeploy script; requirements.txt not needed for DashR apps

.circleci/config.yml
Ensure that `init.R` is copied for each app, rather than using a single package install script across the entire monorepo.
=> Add init.R to config

README.md
The current `README.md` is missing a few details that we might wish to include for future Dash for R app deployments. I have proposed to add them in here.
=> Added R notes to README.md

.circleci/config.yml
This PR proposes to display a helpful error message whenever an app exists in the repository but has not been declared in Dash Enterprise's app manager, or when the entry has been removed prior to redeployment.
=> Add error message/handling for case in which there is no app on Gallery.

README.md
This PR aims to fix handling relative path in README.md.
```
DATA_PATH = pathlib.Path(__file__, "/data")
```  
will result in `/data` at app.py level, this cannot be recognized as correct path.  
parent folder should be defined as 
```
DATA_PATH = pathlib.Path(__file__).parent
```
=> fix pathlib handling in README

apps/dash-wind-streaming/app.py
should help resolve #331. 
After profiling this app with [py-spy](https://github.com/benfred/py-spy), this app running with a 5 tabs open spent 98% of the gunicorn resources updating graphs and most of that time was spent by plotly.py validating them. Getting rid of the go objects reduced the time spent updating the graphs to 33%
Before (using go objects)
After (using dicts) …
=> replace go objects with dicts in wind streaming example to improve perf

apps/dash-oil-and-gas/app.py
fixes https://github.com/plotly/dash-sample-apps/issues/337
Updated deployment on playground **https://dash-playground.plotly.host/dash-oil-and-gas/**
1. map doesn't load because of mishandling of `relayoutData` inside callback - {'autosize': True} is not considered and key is not correct.
After fix mapbox should be loading upon app loading,  and when controls in control panel is updated.
2. Fix a math error raised when `Customized` is set in well-status and no item/category in dropdown.
=> Dash oil and gas app fix

.circleci/config.yml, predeploy.py
https://github.com/plotly/dash-sample-apps/pull/351 made a test deploy of adding new google tag upon playground deployment. 
I went through list in above deployment, and found out that I've missed initializing part of app list (my bad) on server panel.
For apps that have been deployed successfully, only one app `dash-nlp` is encountering problem because it declared `SERVER` instead of `server` in Procfile so `predeploy` is unable to locate `app:SERVER`. Handled by https://github.com/plotly/dash-sample-apps/commit/17cd6c840c71178e95138d6fbf552cd50ce8eeb8
This PR does minor fix including:
@shammamah  Let me know whether we could get this merged before meeting with @VeraZab for a checkup.
=> #351 follow up

apps/dash-object-detection/app.py
Issue for app: https://github.com/plotly/dash-sample-apps/issues/396
Graphs on the app are not updated at a dcc.Interval of 700ms.
The graph didn't get updated at front-end because the original app has too frequent dcc.Intervals(2 x 700ms and 1 x 100ms), each 700ms updates a dcc.Graph, accumulated network requests(callstack overflow) and cannot send updated graphs back to front end. Note that dash-player component itself has an interval dcc.Interval at 100ms to update itself and this already poses a pressure on networks.
This PR removes extra dcc.Intervals, reduces updating frequency to every 1000ms(whereas requests from updating graphs takes avg 300-500ms here).
Check on https://dash-playground.plotly.host/dash-object-detection/ to see performance improve.
I have addressed all of the …
=> Object detection app fix

apps/dash-mapd-demo/assets/dash-mapd.css, apps/dash-uber-rides-demo/assets/style.css, apps/dashr-uber-rides/assets/style.css
Issue for apps: dash / dashr Uber apps, mapd-demo
I noticed that all the apps that use `base.css` and the date picker components have an issue in that the calendars don't display the full week because of padding being added to `td` in `base.css`. So the header shows all 7 days of the week, but the dates for Saturdays are being pushed and aren't actually accessible to the user
This is an issue in the uber apps, and in the mapd-demo app. I've unset the padding on `.CalendarMonth_table td` in each of their respective stylesheets, which fixes the issue without inadvertently messing up the style for other `td` elements:
=> css fix for calendar alignment issues

.circleci/config.yml, deploy
At the moment, apps that require either will fail to deploy.
Note that this may end up linking an app twice to a service, so we need to audit this roll-out to 'recreate' those apps.
N/A
=> feat: add support for creating redis/postgres services if needed

apps/dash-cytoscape-lda/requirements.txt
=> [FIX] Dash-cytoscape-lda: Downgrade scikit-learn to 0.20.1

apps/dash-oil-and-gas/requirements.txt
Upgrading this app to use dash==1.12.0 . The upgrade will allow for a domain restriction to be placed on the mapbox token for the gallery apps without encountering map rendering issues. See #426  for details
- Current gallery app URL: https://dash-gallery.plotly.host/dash-oil-and-gas/
readable and, where it isn't, it …
=> bumping dash-oil-and-gas to dash==1.12.0

apps/dash-uber-rides-demo/requirements.txt
Upgrading this app to use dash==1.12.0 . The upgrade will allow for a domain restriction to be placed on the mapbox token for the gallery apps without encountering map rendering issues. See #426  for details
- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-uber-rides-demo/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-uber-rides-demo/
I have …
=> updating dash-uber-rides-demo to dash 1.12.0

apps/dash-image-enhancing/ColabDemo.ipynb
=> Fix `app.run_server` in Dash Image Enhancing Notebook

.deployignore
For continual cost saving measures, we are removing this demo application as it costs ~$200/m and doesn't directly drive value.
=> add dash-mapd-demo to .deployignore for cost savings

apps/dashr-ncbi-explorer/.buildpacks, apps/dashr-ncbi-explorer/app.R, apps/dashr-ncbi-explorer/init.R
This PR proposes to update `app$layout` such that the specification of components is contained with a list, which is wrapped within `htmlDiv`. The previous layout definition was supported prior to plotly/dashR#121, but now results in an error. The changes should restore the app's functionality.
=> Fix layout declaration for dashr-ncbi-explorer

.github/workflows/main.yml, README.md
Closes #559
Whenever a commit is pushed to master:
- Automatically bump version
- Compress each app directory into a zip file
- Create a release and upload all the zipped apps …
=> Add automation to automatically release zipped apps

apps/dbc-soccer-analytics/app.py
#patch
Goal is to trigger rebuild on master
readable and, where it isn't, it has been …
=> Trigger soccer analytics to rebuild on gallery

apps/dash-image-processing/app.py, apps/dash-interest-rate/app.py, apps/dash-loan-grade/app.py
For a few apps here, we want to add a fallback to an external database environment variable if the internal database doesn't work. This ensures compatibility with both Single server and DEK 4.x
=> Add external database fallback

CONTRIBUTING.md, README.md
The current readme contains a lot of internal information that might not be useful for most users visiting the repository, and the starting paragraph is a bit hard to understand.
I made those small changes (click here for [readme](https://github.com/plotly/dash-sample-apps/blob/3e426bdc79dce26d4aef127e68d90ab2ab1684b0/README.md)):
* Rewrite the starting paragraph to be clearer
* Move up the zip download instructions to be the first thing any user sees
* Everything else to a "Contributing.md" file
Let me know if those changes make sense!
Closes https://github.com/plotly/dash-sample-apps/issues/633
=> Refactor Readme and add a contributing doc
